# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbde84edd69eaf581168deeb07bc9d52c3d66b461b93b2f7860855f39a005e3c62b14a8f8b4bd4cc319074238518f0f37fc61af6aad25823aa36f155ee81a66d

test:
  secret_key_base: c562e206317479f3503ce50f6782cb1703788e8e3671b848fe8afc1d66a91557a005939f46160f46f1d5b0fe26d163c14afe6f8382d25261fcab88e6b195317f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
